name: Render Screenshots



on: [push]
jobs:
  screenshots:
    runs-on: ubuntu-latest

    env:
      URLS: |
        https://pureleap.com

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      
      - name: Take screenshots
        run: |
          cd packages/ui
          yarn playwright install --with-deps
          yarn node scripts/screenshot.js

      - name: Upload screenshots
        run: |
          for file in packages/ui/screenshots/**/*.png; do
            name=$(basename "$file" .png)
            echo "Uploading $file as $name"
            gh artifact upload "$name" "$file"
          done
